#Possible Values: gen_splits (Generate 3D train/test/validation split. Configurations under the tag 'split' will be used.),
# gen_images (Generate 2D train/test/validation split. Configurations under the tag '2D' will be used.)
mode: "gen_splits"
split:
  input_paths: "Data/T1_1/,Data1/T1_2/" # Comma-separated (without-spaces) list of input of paths.
  scan_ext: "_T1_BC_bet.nii.gz" # File extension of input scan.
  msk_ext: "LESION.nii.gz" # File extension of lesion mask.
  type: "balanced" #Possible options: Default (Random Split of data), balanced (Generate splits with equal representation of each voxel split.)
  train_ratio: 0.8
  test_ratio: 0.2
  valid_ratio: 0.2 # Taken from the training set. Should be < train_ratio / 2.
  seed: 0000
  do_patching: True
  do_augmentation: False
  rmv_pre_aug: False # Remove augmented files. Any file ending with _cm from the input folder(s) will be deleted.
  # -- Patching Configurations -- #
  patch:
    shape: "(128, 128, 128)"
    random: False # Generate random patches or ordered patches.
    stride:
      train: 4
      valid: 8
      test: 8
    alw_empty_patches: False # Allow empty patches; only used for training set.
# -- Only used if type = balanced -- #
  balanced:
    bin_range: "0, 100, 1000, 5000, 10000, 100000" #List of ranges for the voxels to be divided into. If empty, bins will be generated.
    save_ordered_set: True
    read_from_file: True # If ordered_set.csv is already generated, bins could be read from the file rather than re-generating the bins.
    visualise_dataset: True
# -- Training set will be augmented using CraveMix -- #
  augmentation:
    factor: 0.3


